owner: "echoIA Community"
copyright_start_year: 2025

site_content_license_name: "CC BY 4.0"
site_content_license_url: "https://creativecommons.org/licenses/by/4.0/"

metadata_license_name: "CC0 1.0"
metadata_license_url: "https://creativecommons.org/publicdomain/zero/1.0/"

code_license_name: "MIT"
code_license_url: "https://opensource.org/license/mit"
