owner: "echoIA Community"

site_content_license_name: "CC BY 4.0"
site_content_license_url: "https://creativecommons.org/licenses/by/4.0/"

metadata_license_name: "CC0 1.0"
metadata_license_url: "https://creativecommons.org/publicdomain/zero/1.0/"

code_license_name: "MIT"
code_license_url: "https://opensource.org/license/mit"

zenodo_community_url: "https://zenodo.org/communities/echo-ia"  #

url: "https://echo-ia.github.io"   # my user/org site
baseurl: "/shape-catalogs"         # my project repo name
permalink: pretty                  # makes /page/ instead of /page.html

defaults:
  - scope:
      path: "pages"                # everything in /pages
      type: "pages"
    values:
      permalink: "/:basename/"     # /catalogs/, /submit/, /contact/

